services:
  # Backend Django
  - type: web
    name: xbpneus-backend
    env: python
    region: oregon
    plan: starter
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    releaseCommand: "python manage.py migrate"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: xbpneus-db
          property: connectionString
      - key: DJANGO_DEBUG
        value: False
      - key: SESSION_COOKIE_SECURE
        value: True
      - key: CSRF_COOKIE_SECURE
        value: True
      - key: SECURE_SSL_REDIRECT
        value: True
      - key: PAGE_SIZE
        value: 20

  # Frontend React
  - type: web
    name: xbpneus-frontend
    env: node
    region: oregon
    plan: starter
    branch: main
    buildCommand: "cd frontend && npm install && VITE_API_URL=https://xbpneus-backend.onrender.com npm run build"
    startCommand: "cd frontend && npx serve -s dist -l $PORT"
    envVars:
      - key: NODE_VERSION
        value: 22.13.0
      - key: VITE_API_URL
        value: https://xbpneus-backend.onrender.com

databases:
  - name: xbpneus-db
    databaseName: xbpneus
    user: xbpneus
    region: oregon
    plan: free
